FROM bitnami/spark:3.5

USER root

RUN install_packages libgomp1 || true

RUN pip install --no-cache-dir \
    torch==2.2.* \
    numpy \
    pandas \
    pyhive \
    thrift \
    thrift-sasl \
    hdfs \
    sasl \
    sqlalchemy \
    pymysql

COPY spark-defaults.conf /opt/bitnami/spark/conf/spark-defaults.conf

USER 1001
